- name: Securely change root password and record it
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true

  tasks:
    - name: Generate a new secure password for root
      ansible.builtin.set_fact:
        root_new_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

    - name: Apply new, hashed password to the 'root' user
      ansible.builtin.user:
        name: root
        password: "{{ root_new_password | password_hash('sha512', rounds=5000) }}"

    - name: Record the new password securely
      ansible.builtin.copy:
        content: "Host: {{ inventory_hostname }} | New Root Password: {{ root_new_password }}"
        dest: "./downloads/{{ inventory_hostname }}"
        mode: '0600'
      delegate_to: localhost
      changed_when: false # Prevent this task from reporting as 'changed'

    - name: Display a success message and location of the recorded passwords
      ansible.builtin.debug:
        msg: "Root password changed successfully on {{ inventory_hostname }}. The new password has been recorded securely to a local file for this host."
