- name: "Run role vm_configuration"
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  roles:
      - role: vm_configuration

# Example run:
# ansible-playbook -i inventory/ -i vars/ -e "target_hosts=myhost" configure-vm.yml \
# --skip-tags vmc.setup-accounts-and-privileges \
# --skip-tags vmc.configure-security --skip-tags vmc.configure-sshd
