- name: Create new technical user
  hosts: "{{ target_hosts }}"
  vars_files:
    - vars/external-vars.yml
  become: yes
  tasks:

    - name: Checking which group is available - sudo or wheel
      shell: |
        if grep -q sudo /etc/group
        then
            echo "sudo"
            exit 0
        elif grep -q wheel /etc/group; then
            echo "wheel"
            exit 0
        else
            echo "Unknown admin group"
            exit 1
        fi
      register: admingroup
      changed_when: admingroup.rc == 1

    - debug:
       msg: "Available group: {{ admingroup.stdout }}"

    - name: Create new technical user {{ technical_user }}
      user: 
        name: "{{ technical_user }}"
        # Do not create password, only key will allow to login
        shell: /bin/bash
        create_home: yes
        append: yes
        groups: "{{ admingroup.stdout }}"

    - name: Test if /etc/sudoers.d/{{ technical_user }} exists
      stat:
        path: /etc/sudoers.d/{{ technical_user }}
      register: stat_result

    - name: Allow {{ technical_user }} to have passwordless sudo
      lineinfile:
        path: /etc/sudoers.d/{{ technical_user }}
        state: present
        line: "# Created automatically by Ansible\n{{ technical_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
        create: yes
      when: not stat_result.stat.exists

    - name: Add ssh key to user {{ technical_user }}
      authorized_key:
        user: "{{ technical_user }}"
        state: present
        key: "{{ technical_user_pubkey }}"
    
    