- name: Install OpenVPN server
  hosts: "{{ target_hosts | default('all') }}"
  vars_files:
    - vars/external-vars.yml
  become: true
  tasks:

    - name: Clone git repo with OpenVPN installer
      ansible.builtin.git:
        repo: https://github.com/angristan/openvpn-install.git
        dest: /tmp/openvpn-install
        force: true

    - name: Replace IP address space
      ansible.builtin.replace:
        path: /tmp/openvpn-install/openvpn-install.sh
        regexp: '10.8.0'
        replace: "{{ openvpn_address_space }}"

    - name: Run shell script
      # Old convention used because of issues with setting env variables
      shell: |
          chmod +x /tmp/openvpn-install/openvpn-install.sh
          /tmp/openvpn-install/openvpn-install.sh
      environment:
        # https://github.com/angristan/openvpn-install/blob/master/README.md
        AUTO_INSTALL: y
        APPROVE_INSTALL: y
        APPROVE_IP: y
        IPV6_SUPPORT: n
        PORT_CHOICE: 2
        PORT: "{{ openvpn_server_port }}"
        PROTOCOL_CHOICE: 1
        DNS: 1
        COMPRESSION_ENABLED: n
        CUSTOMIZE_ENC: n
        CLIENT: client-001
        PASS: 1
      args:
        warn: false

    - name: Download certificate for client-001
      ansible.builtin.fetch:
        src: /home/{{ technical_user }}/client-001.ovpn
        dest: downloads/client-001.ovpn
        flat: true
