- name: Provision node-exporter
  hosts: "{{ target_hosts | default('all') }}"
  vars_files:
    - vars/external-vars.yml
  become: yes
  pre_tasks:

    - name: Create node_exporter cert dir
      file:
        path: "/etc/node_exporter"
        state: directory
        owner: root
        group: root

    - name: Copy certs
      copy:
        src: resources/node_exporter/{{ inventory_hostname }}/
        dest: /etc/node_exporter/
        owner: root
        group: root
        mode: 700

  roles:
    - prometheus.prometheus.node_exporter
