- name: Provision node-exporter
  hosts: "{{ target_hosts }}"
  become: yes
  pre_tasks:

    - name: Create node_exporter cert dir
      file:
        path: "/etc/node_exporter"
        state: directory
        owner: root
        group: root

    - name: Copy certs
      copy:
        src: "resources/node_exporter/{{ item }}"
        dest: "/etc/node_exporter/{{ item | basename }}"
        owner: root
        group: root
        mode: 700
      loop:
        - "{{ inventory_hostname }}/{{ inventory_hostname }}.crt"
        - "{{ inventory_hostname }}/{{ inventory_hostname }}.key"

  roles:
    - prometheus.prometheus.node_exporter
