---
collections:
  - name: "community.general"
    version: 11.1.0
  - name: "ansible.posix"
    version: 2.1.0
  - name: "devsec.hardening"
    version: 10.3.0
  - name: "prometheus.prometheus"
    version: 0.27.0
