parameters:
  - name: jobName
    type: string
  - name: dependsOn
    type: string
    default: ''
  - name: imageName
    type: string
  - name: pythonExecutable
    type: string
  - name: pipExecutable
    type: string

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: succeeded()
  pool:
    name: mdp-adotest-dev-ncus-01
    demands:
      - ImageOverride -equals ${{ parameters.imageName }}
  steps:
    - displayName: 'Check environment'
      script: id && printenv
    - displayName: 'Update PATH variable'
      script: echo "##vso[task.prependpath]$(HOME)/.local/bin"
    - displayName: 'Check Python version'
      script: ${{ parameters.pythonExecutable }} --version
    - displayName: 'Check Pip version'
      script: ${{ parameters.pipExecutable }} --version
    - displayName: 'Install ansible-core'
      script: ${{ parameters.pipExecutable }} install --user "ansible-core<=2.20.1"
    - displayName: 'Install Ansible dependencies'
      script: ansible-galaxy install -r requirements.yml
    - displayName: 'Test role vm_configuration'
      script: ansible-playbook -i roles/vm_configuration/tests/inventory.yml roles/vm_configuration/tests/test.yml
    - displayName: 'Test role bash_customization'
      script: ansible-playbook -i roles/bash_customization/tests/inventory.yml roles/bash_customization/tests/test.yml
