---
- name: "[02.01] Copy bash_aliases file"
  ansible.builtin.template:
    src: "templates/bash_aliases.j2"
    dest: "/home/{{ bash_customization_default_user }}/.bash_aliases"
    owner: "{{ bash_customization_default_user }}"
    group: "{{ bash_customization_default_group }}"
    mode: "0640"
  tags:
    - always
    - bac.configure-aliases
    - bac.02.01
