---
- name: "[03.01] Generate color for machine name"
  when: bash_customization_ash_hostname_color is not defined or bash_customization_bash_hostname_color | length == 0
  ansible.builtin.shell: "echo $(( RANDOM % 229 ))"
  args:
    executable: /bin/bash
  register: machine_color
  changed_when: false
  tags:
    - always
    - bac.configure-bashrc
    - bac.03.01

- name: "[03.02] Copy bashrc file"
  ansible.builtin.template:
    src: "templates/bashrc.j2"
    dest: "/home/{{ bash_customization_default_user }}/.bashrc"
    owner: "{{ bash_customization_default_user }}"
    group: "{{ bash_customization_default_group }}"
    mode: "0640"
  tags:
    - always
    - bac.configure-bashrc
    - bac.03.02
