---
- name: "[04.01] Copy vimrc file"
  ansible.builtin.template:
    src: "templates/vimrc.j2"
    dest: "/home/{{ bash_customization_default_user }}/.vimrc"
    owner: "{{ bash_customization_default_user }}"
    group: "{{ bash_customization_default_group }}"
    mode: "0640"
  tags:
    - always
    - bac.configure-vim
    - bac.04.01

- name: "[04.02] Create vim dirs"
  ansible.builtin.file:
    path: "/home/{{ bash_customization_default_user }}/.vim/{{ item }}"
    state: directory
    mode: '0750'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    recurse: true
  loop:
    - autoload
    - colors
    - bundle
  tags:
    - always
    - bac.configure-vim
    - bac.04.02

- name: "[04.03] Install pathogen"
  ansible.builtin.get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: "/home/{{ bash_customization_default_user }}/.vim/autoload/pathogen.vim"
    mode: "0750"
    owner: "{{ bash_customization_default_user }}"
    group: "{{ bash_customization_default_group }}"
  tags:
    - always
    - bac.configure-vim
    - bac.04.03

- name: "[04.04] Install color theme"
  ansible.builtin.get_url:
    url: "{{ bash_customization_default_theme_raw }}"
    dest: "/home/{{ bash_customization_default_user }}/.vim/colors/{{ bash_customization_default_theme_raw | basename }}"
    mode: "0750"
    owner: "{{ bash_customization_default_user }}"
    group: "{{ bash_customization_default_group }}"
  tags:
    - always
    - bac.configure-vim
    - bac.04.04

- name: "[04.05] Pull required vim addons from github"
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/home/{{ bash_customization_default_user }}/.vim/bundle/{{ (item.url | basename | split('.git'))[0] }}"
    recursive: true
    version: "{{ item.branch }}"
    # Ensure that during next run there will be no errors with local changes
    force: true
    depth: 1
    single_branch: true
  loop: "{{ bash_customization_vim_repos }}"
  tags:
    - always
    - bac.configure-vim
    - bac.04.05

- name: "[04.06] Update ownership to .vim directory"
  ansible.builtin.file:
    path: /home/{{ bash_customization_default_user }}/.vim
    owner: "{{ bash_customization_default_user }}"
    group: "{{ bash_customization_default_group }}"
    mode: "0750"
    state: directory
    recurse: true
  tags:
    - always
    - bac.configure-vim
    - bac.04.06
