---
- name: "[05.01] Create tmux plugins dir"
  ansible.builtin.file:
    path: "/home/{{ bash_customization_default_user }}/.tmux/plugins"
    state: directory
    mode: '0750'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    recurse: true
  tags:
    - always
    - bac.configure-tmux
    - bac.05.01

- name: "[05.02] Pull required tmux addons from github"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "/home/{{ bash_customization_default_user }}/.tmux/plugins/tpm"
    recursive: true
    version: master
    # Ensure that during next run there will be no errors with local changes
    force: true
    depth: 1
    single_branch: true
  tags:
    - always
    - bac.configure-tmux
    - bac.05.02

- name: "[05.03] Copy tmux config template"
  ansible.builtin.template:
    src: "templates/tmux.conf.j2"
    dest: "/home/{{ bash_customization_default_user }}/.tmux.conf"
    owner: "{{ bash_customization_default_user }}"
    group: "{{ bash_customization_default_group }}"
    mode: "0640"
  tags:
    - always
    - bac.configure-tmux
    - bac.05.03

- name: "[05.04] Update ownership to .tmux directory"
  ansible.builtin.file:
    path: /home/{{ bash_customization_default_user }}/.tmux
    owner: "{{ bash_customization_default_user }}"
    group: "{{ bash_customization_default_group }}"
    mode: "0750"
    state: directory
    recurse: true
  tags:
    - always
    - bac.configure-vim
    - bac.05.04
