---
apt_gpg_key_extension: "{{ item.apt_gpg_url | basename | split('.') | last | default('gpg') }}"

architecture_map:
  "x86_64":
    "amd64"
  "aarch64":
    "arm64"
  "aarch":
    "arm64"
  "armhf":
    "armhf"
  "armv7l":
    "armhf"

packages_to_install:
  common:
    - "sudo"
    - "tar"
    - "vim"
    - "htop"
    - "traceroute"
    - "net-tools"
    - "git"
    - "wget"
    - "ufw"
    - "bash-completion"
    - "python3-pip"
    - "python3-setuptools"
    - "tmux"
    - "lsof"
    - "curl"
    - "ca-certificates"
    - "kubectl"
    - "podman"
  redhat:
    - "iputils"
    - "lm_sensors"
    - "cronie"
  debian:
    - "iputils-ping"
    - "lm-sensors"
    - "cron"
    - "apt-transport-https"
    - "gnupg-agent"
    - "software-properties-common"

repo_list:
  - name: "kubernetes"
    apt_repo_url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    apt_gpg_url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
    yum_repo_url: "https://pkgs.k8s.io/core:/stable:/v1.29/rpm/"
    yum_gpg_url: "https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key"
    yum_excludes: '"kubelet kubeadm cri-tools kubernetes-cni"'
  - name: "vscode"
    apt_repo_url: "https://packages.microsoft.com/repos/code stable main"
    apt_gpg_url: "https://packages.microsoft.com/keys/microsoft.asc"
    yum_repo_url: "https://packages.microsoft.com/yumrepos/vscode"
    yum_gpg_url: "https://packages.microsoft.com/keys/microsoft.asc"
    yum_excludes: '""'
  - name: "hasihcorp"
    apt_repo_url: "https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    apt_gpg_url: "https://apt.releases.hashicorp.com/gpg"
    yum_repo_url: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    yum_gpg_url: "https://rpm.releases.hashicorp.com/gpg"
    yum_excludes: '""'
  - name: "helm"
    apt_repo_url: "https://baltocdn.com/helm/stable/debian/ all main"
    apt_gpg_url: "https://baltocdn.com/helm/signing.asc"
    yum_repo_url: ""
    yum_gpg_url: ""
    yum_excludes: ""
