---
create_default_user: true

create_technical_user: true

apt_gpg_key_extension: "{{ item.apt_gpg_url | basename | split('.') | last | default('gpg') }}"

architecture_map:
  "x86_64":
    "amd64"
  "aarch64":
    "arm64"
  "aarch":
    "arm64"
  "armhf":
    "armhf"
  "armv7l":
    "armhf"

packages_to_install:
  # Common packages
  - "sudo"
  - "tar"
  - "vim"
  - "htop"
  - "traceroute"
  - "net-tools"
  - "git"
  - "wget"
  - "ufw"
  - "bash-completion"
  - "python3-pip"
  - "python3-setuptools"
  - "tmux"
  - "lsof"
  # Debian-specific packages
  - "iputils"
  - "lm_sensors"
  - "cronie"
  # Redhat-specific versions
  - "iputils-ping"
  - "lm-sensors"
  - "cron"
  # kubectl packages
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "gnupg-agent"
  - "software-properties-common"
  # podman
  - podman
  # kubectl
  - kubectl

repo_list:
  - name: "kubernetes"
    apt_repo_url: "https://apt.kubernetes.io/ kubernetes-xenial main"
    apt_gpg_url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    yum_repo_url: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch"
    yum_gpg_url: "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  - name: "vscode"
    apt_repo_url: "https://packages.microsoft.com/repos/code stable main"
    apt_gpg_url: "https://packages.microsoft.com/keys/microsoft.asc"
    yum_repo_url: "https://packages.microsoft.com/yumrepos/vscode"
    yum_gpg_url: "https://packages.microsoft.com/keys/microsoft.asc"
  - name: "hasihcorp"
    apt_repo_url: "https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    apt_gpg_url: "https://apt.releases.hashicorp.com/gpg"
    yum_repo_url: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    yum_gpg_url: "https://rpm.releases.hashicorp.com/gpg"
  - name: "helm"
    apt_repo_url: "https://baltocdn.com/helm/stable/debian/ all main"
    apt_gpg_url: "https://baltocdn.com/helm/signing.asc"
    yum_repo_url: ""
    yum_gpg_url: ""

ufw_rules:
  - comment: "Allow sshd on custom port"
    direction: "in"
    from_ip: "any"
    proto: "tcp"
    rule: "allow"
    to_port: "28828"
  - comment: "Allow node-exporter"
    direction: "in"
    from_ip: "any"
    proto: "tcp"
    rule: "allow"
    to_port: "40244"
