---
- name: "[04.01] Include dev-sec ssh_hardening role"
  ansible.builtin.include_role:
    name: ssh_hardening
  vars:
    ssh_client_hardening: "{{ vm_configuration_ssh_client_hardening }}"
    ssh_server_ports: "{{ vm_configuration_ssh_server_ports }}"
    ssh_host_key_files: "{{ vm_configuration_ssh_host_key_files }}"
    ssh_host_rsa_key_size: "{{ vm_configuration_ssh_host_rsa_key_size }}"
    ssh_client_alive_interval: "{{ vm_configuration_ssh_client_alive_interval }}"
    ssh_client_alive_count: "{{ vm_configuration_ssh_client_alive_count }}"
    ssh_permit_tunnel: "{{ vm_configuration_ssh_permit_tunnel }}"
    ssh_permit_root_login: "{{ vm_configuration_ssh_permit_root_login }}"
    ssh_allow_tcp_forwarding: "{{ vm_configuration_ssh_allow_tcp_forwarding }}"
    ssh_gateway_ports: "{{ vm_configuration_ssh_gateway_ports }}"
    ssh_allow_agent_forwarding: "{{ vm_configuration_ssh_allow_agent_forwarding }}"
    ssh_x11_forwarding: "{{ vm_configuration_ssh_x11_forwarding }}"
    ssh_use_pam: "{{ vm_configuration_ssh_use_pam }}"
    ssh_gssapi_support: "{{ vm_configuration_ssh_gssapi_support }}"
    ssh_kerberos_support: "{{ vm_configuration_ssh_kerberos_support }}"
    ssh_allow_users: "{{ vm_configuration_ssh_allow_users }}"
    sftp_enabled: "{{ vm_configuration_sftp_enabled }}"
    sshd_moduli_minimum: "{{ vm_configuration_sshd_moduli_minimum }}"
    ssh_challengeresponseauthentication: "{{ vm_configuration_ssh_challengeresponseauthentication }}"
    ssh_server_password_login: "{{ vm_configuration_ssh_server_password_login }}"
    ssh_banner: "{{ vm_configuration_ssh_banner }}"
    ssh_compression: "{{ vm_configuration_ssh_compression }}"
    ssh_login_grace_time: "{{ vm_configuration_ssh_login_grace_time }}"
    ssh_max_auth_retries: "{{ vm_configuration_ssh_max_auth_retries }}"
    ssh_max_sessions: "{{ vm_configuration_ssh_max_sessions }}"
    ssh_server_enabled: "{{ vm_configuration_ssh_server_enabled }}"
    ssh_server_hardening: "{{ vm_configuration_ssh_server_hardening }}"
    ssh_use_dns: "{{ vm_configuration_ssh_use_dns }}"
    ssh_macs: "{{ vm_configuration_ssh_macs }}"
    ssh_kex: "{{ vm_configuration_ssh_kex }}"
    ssh_ciphers: "{{ vm_configuration_ssh_ciphers }}"
    sshd_log_level: "{{ vm_configuration_sshd_log_level }}"
    sshd_strict_modes: "{{ vm_configuration_sshd_strict_modes }}"
    sshd_authenticationmethods: "{{ vm_configuration_sshd_authenticationmethods }}"
  collections:
    - devsec.hardening
  tags:
    - always
    - vmc.configure-sshd
    - vmc.04.01
