---
- name: "[04.01] Include dev-sec ssh_hardening role"
  ansible.builtin.include_role:
    name: ssh_hardening
  collections:
    - devsec.hardening
  tags:
    - always
    - vmc.configure-sshd
    - vmc.04.01
