trigger:
  - master

strategy:
  matrix:
    ubuntu22:
      imageName: 'ubuntu22-ado'
      pipExecutable: 'pip3'
      pythonExecutable: 'python3'
    redhat8:
      imageName: 'rhel8-ado'
      pipExecutable: 'pip3.9'
      pythonExecutable: 'python3.9'

pool:
  name: mdp-adotest-dev-ncus-01
  demands:
    - ImageOverride -equals $(imageName)

steps:
  - script: id && printenv
    displayName: 'Check environment'
  - script: echo "##vso[task.prependpath]$(HOME)/.local/bin"
    displayName: 'Update PATH variable '
  - script: $(pythonExecutable) --version
    displayName: 'Check Python version'
  - script: $(pipExecutable) --version
    displayName: 'Check Pip version'
  - script: $(pipExecutable) install --user "ansible-core<=2.16.14" "ansible-lint<=25.6.1"
    displayName: 'Install required packages'
  - script: ansible-lint --version
    displayName: 'Run ansible-lint'
  - script: ansible --version
    displayName: 'Run ansible'
