trigger:
  - master

jobs:
  - job: Lint
    displayName: 'Static Analysis (ansible-lint)'
    pool:
      name: mdp-adotest-dev-ncus-01
      demands:
        - ImageOverride -equals ubuntu22-ado
    steps:
      - displayName: 'Install required packages'
        script: pip3 install --user "ansible-core<=2.20.1" "ansible-lint<=26.1.1"
      - displayName: 'Update PATH variable'
        script: echo "##vso[task.prependpath]$(HOME)/.local/bin"
      - displayName: 'Run ansible-lint'
        script: shopt -s globstar; ansible-lint **/*.yml

  - template: templates/ansible-test-job.yaml
    parameters:
      jobName: Test_Ubuntu22
      dependsOn: Lint   
      imageName: 'ubuntu22-ado'
      pipExecutable: 'pip3'
      pythonExecutable: 'python3'

  - template: templates/ansible-test-job.yaml
    parameters:
      jobName: Test_RedHat8
      dependsOn: Test_Ubuntu22
      imageName: 'rhel8-ado'
      pipExecutable: 'pip3.9'
      pythonExecutable: 'python3.9'
