trigger:
  - master

pool:
  name: mdp-adotest-dev-ncus-01
  demands:
    - ImageOverride -equals ubuntu-ado

stages:
  - stage: Tests
    jobs:
      - job: PrepareAndRunTests
        steps:
          - script: id && printenv
            displayName: 'Check environment'
          - script: pyenv global 3.12.11
            displayName: 'Check Python version'
          - script: python3 --version
            displayName: 'Check Python version'
          - script: pip3 install -r requirements.txt
            displayName: 'Install Python packages'
          - script: ansible-lint .
            displayName: 'Run ansible-lint'
          - script: ansible --version
            displayName: 'Run ansible'
