# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  name: mdp-adotest-dev-ncus-01

stages:
  - stage: Preparation
    jobs:
      - job: InstallPackages
        steps:
          - script: pip3 install -r requirements.txt
            displayName: 'Install python packages'
  - stage: Tests
    jobs:
      - job: RunLinter
        steps:
          - script: ansible-lint .
            displayName: 'Run ansible-lint'
      - job: RunAnsible
        steps:
          - script: ansible --version
            displayName: 'Run ansible'

