trigger:
  - master

stages:
  - stage: StaticAnalysis
    jobs:
      - job: StaticAnalysis
        pool:
          name: mdp-adotest-dev-ncus-01
          demands:
            - ImageOverride -equals ubuntu22-ado
        steps:
          - script: pip3 install --user "ansible-core<=2.20.1" "ansible-lint<=26.1.1"
            displayName: 'Install required packages'
          - script: echo "##vso[task.prependpath]$(HOME)/.local/bin"
            displayName: 'Update PATH variable'
          - script: shopt -s globstar; ansible-lint **/*.yml
            displayName: 'Run ansible-lint'

  - stage: FunctionalTestsUbuntu22
    dependsOn: StaticAnalysis
    jobs:
      - template: templates/ansible-test-job.yaml
        parameters:
          jobName: FunctionalTestsUbuntu22
          imageName: 'ubuntu22-ado'
          pipExecutable: 'pip3'
          pythonExecutable: 'python3'

  - stage: FunctionalTestsRHEL9
    dependsOn: FunctionalTestsUbuntu22
    jobs:
      - template: templates/ansible-test-job.yaml
        parameters:
          jobName: FunctionalTestsRHEL9
          imageName: 'rhel9-ado'
          pipExecutable: 'pip3.12'
          pythonExecutable: 'python3.12'
