def privateRegistryAddress = 'nexus3.k8s.lan:50000'

pipeline {
    agent {
        kubernetes {
            inheritFrom 'customnode'
            yaml """
            spec:
              containers:
                - name: redhat8-ansible
                  image: "${privateRegistryAddress}/redhat8-ansible:1.0"
                  command:
                  - "sleep"
                  args:
                  - "999999"
                  restartPolicy: Never
                  volumeMounts:
                  - mountPath: "/ansible_workspace"
                    name: "workspace-volume"
                    readOnly: false
                  imagePullPolicy: Always
                - name: ubuntu-ansible
                  image: "${privateRegistryAddress}/ubuntu-ansible:1.0"
                  command:
                  - "sleep"
                  args:
                  - "999999"
                  restartPolicy: Never
                  volumeMounts:
                  - mountPath: "/ansible_workspace"
                    name: "workspace-volume"
                    readOnly: false
                  imagePullPolicy: Always
            """
        }
    }
    options {
        buildDiscarder(
            logRotator(numToKeepStr: '5')
        )
        timestamps()
        disableConcurrentBuilds()
        timeout(
            time: 1,
            unit: 'HOURS'
        )
        durabilityHint('PERFORMANCE_OPTIMIZED')
        ansiColor('xterm')
    }
    environment {
        // Redefine workspace because of custom path
        WORKSPACE_ANSIBLE = "workspace/${env.WORKSPACE.split('/').last()}"
        SINGLE_PLAYBOOK_PATH = "${env.WORKSPACE_ANSIBLE}/${env.SINGLE_PLAYBOOK_PATH}"
        //ROLE_ROOT_PATH = "${env.WORKSPACE_ANSIBLE}/${env.ROLE_ROOT_PATH}"
        ROLE_PLAYBOOK_PATH = "${env.WORKSPACE_ANSIBLE}/${env.ROLE_ROOT_PATH}/tests/test.yml"
    }
    parameters {
        string(
            defaultValue: '',
            description: 'Pass relative path of playbook to be tested (if it is a single playbook)',
            name: 'SINGLE_PLAYBOOK_PATH',
            trim: true
        )
        string(
            defaultValue: '',
            description: 'Pass relative path to root of role (if it is a role)',
            name: 'ROLE_ROOT_PATH',
            trim: true
        )
        string(
            defaultValue: '',
            description: 'Additional ansible params like --skip-tags etc.',
            name: 'ANSIBLE_ADDITIONAL_PARAMS',
            trim: true
        )
    }
    stages {
        /* Enable step if using no multibranch pipeline
        stage('Pull Repository') {
            steps {
                git(
                    credentialsId: 'github-access-token-mrachuta',
                    url: 'https://github.com/mrachuta/ansible-resources.git',
                    branch: 'develop'
                )
            }
        }
        */
        stage('Run ansible-lint') {
            steps {
                script {
                    withEnv(["PATH+EXTRA=/home/jenkins/.local/bin"]) {
                        sh 'pip3 install ansible-core==2.12 mitogen==0.3.3 ansible-lint==6.12'
                        if (env.ROLE_ROOT_PATH.length() != 0) {
                            dir(env.ROLE_ROOT_PATH) {
                                sh 'ansible-lint -p -v .'
                                recordIssues(
                                    enabledForFailure: true,
                                    ignoreQualityGate: true,
                                    skipBlames: true,
                                    skipPublishingChecks: true,
                                    sourceDirectories: [
                                        [path: '.']
                                    ],
                                    tools: [
                                        ansibleLint(skipSymbolicLinks: true)
                                    ]
                                )
                            }
                        } else {
                            sh 'ansible-lint -p -v ${SINGLE_PLAYBOOK_PATH}'
                            recordIssues(
                                enabledForFailure: true,
                                ignoreQualityGate: true,
                                skipBlames: true,
                                skipPublishingChecks: true,
                                sourceDirectories: [
                                    [path: env.SINGLE_PLAYBOOK_PATH]
                                ],
                                tools: [
                                    ansibleLint(skipSymbolicLinks: true)
                                ]
                            )
                        }
                    }
                }
            }
        }
        stage('Run Sonarqube analysis') {
            steps {
                script {
                    env.SONAR_PROJECT_KEY = "ansible-${env.ROLE_ROOT_PATH.split('/')[0]}-${env.ROLE_ROOT_PATH.split('/')[1]}"
                    env.SONAR_PROJECT_NAME = "Ansible ${env.ROLE_ROOT_PATH.split('/')[0]} - ${env.ROLE_ROOT_PATH.split('/')[1]}"
                    env.SONAR_FILES_TO_INCLUDE = "${env.ROLE_ROOT_PATH}**"
                    def scannerHome = tool('sonarqube_scanner_default')
                    def nodeHome = tool('nodejs_default')
                    withEnv(["PATH+EXTRA=${scannerHome}/bin:${nodeHome}/bin"]) {
                        withSonarQubeEnv('sonarqube_default') {
                            sh('sonar-scanner')
                        }
                        timeout(time: 10, unit: 'MINUTES') {
                            def qg = waitForQualityGate()
                            if (qg.status != 'OK') {
                                error "Pipeline aborted due to quality gate failure: ${qg.status}"
                            } else {
                                sonarQGStatus = qg.status
                            }
                        }
                    }
                }
            }
        }
        stage('Run tests') {
            parallel {
                stage('Run tests on redhat8') {
                    steps {
                        script {
                            // Define PLAYBOOK_PATH basing on current param
                            if (env.ROLE_ROOT_PATH.length() != 0) {
                                env.PLAYBOOK_PATH = env.ROLE_PLAYBOOK_PATH
                            } else {
                                env.PLAYBOOK_PATH = env.SINGLE_PLAYBOOK_PATH
                            }
                            env.CONTAINER_NAME = 'redhat8-ansible'
                            container(env.CONTAINER_NAME) {
                                sh 'ansible-wrapper'
                            }
                        }
                    }
                }
                stage('Run tests on ubuntu') {
                    steps {
                        script {
                            if (env.ROLE_ROOT_PATH.length() != 0) {
                                env.PLAYBOOK_PATH = env.ROLE_PLAYBOOK_PATH
                            } else {
                                env.PLAYBOOK_PATH = env.SINGLE_PLAYBOOK_PATH
                            }
                            env.CONTAINER_NAME = 'ubuntu-ansible'
                            container(env.CONTAINER_NAME) {
                                sh 'ansible-wrapper'
                            }
                        }
                    }
                }
            }
        }
    }
}
